# Generated by Django 3.0.3 on 2024-11-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', 'update_hotel_names'),
        ('booking', 'merge_hotel_names'),
    ]

    operations = [
    ]
