# Generated by Django 3.0.3 on 2024-11-18 09:12
# Migration này thực hiện nhiều thay đổi quan trọng cho các model

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_room'),
        ('booking', '0001_rating'),
    ]

    operations = [
        # Xóa options của model Rooms
        migrations.AlterModelOptions(
            name='rooms',
            options={},
        ),
        # Xóa trường deposit_amount khỏi model Booking
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        # Xóa trường hotel_name khỏi model Rooms
        migrations.RemoveField(
            model_name='rooms',
            name='hotel_name',
        ),
        # Thêm trường rating cho model Rooms
        migrations.AddField(
            model_name='rooms',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        # Thêm trường rating_count cho model Rooms
        migrations.AddField(
            model_name='rooms',
            name='rating_count',
            field=models.IntegerField(default=10),
        ),
        # Các thay đổi khác về kiểu dữ liệu và ràng buộc
        # ...
    ]
