# Generated by Django 3.0.3 on 2024-11-18 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_room'),
        ('booking', '0001_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='hotel_name',
        ),
        migrations.AddField(
            model_name='rooms',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='rooms',
            name='rating_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Customer'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_no',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
