# Generated by Django 3.0.3 on 2024-11-18 09:19
# Migration này điều chỉnh các trường rating trong model Rooms

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0002_auto_20241118_1612'),
    ]

    operations = [
        # Cho phép trường rating có thể null
        migrations.AlterField(
            model_name='rooms',
            name='rating',
            field=models.FloatField(default=4.5, null=True),
        ),
        # Cho phép trường rating_count có thể null
        migrations.AlterField(
            model_name='rooms',
            name='rating_count',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
