# Generated by Django 3.0.3 on 2024-11-18 09:30
# Migration này điều chỉnh giá trị mặc định cho các trường

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0004_auto_20241118_1620'),
    ]

    operations = [
        # Thay đổi giá trị mặc định của rating_count từ 10 xuống 5
        migrations.AlterField(
            model_name='rooms',
            name='rating_count',
            field=models.IntegerField(default=5, null=True),
        ),
        # Bỏ giá trị mặc định của start_date
        migrations.AlterField(
            model_name='rooms',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
