# Generated by Django 3.0.3 on 2024-11-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20241118_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rating_count',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
