# Generated by Django 3.0.3 on 2024-11-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_room'),
        ('booking', '0005_auto_20241118_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.RoomManager'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(blank=True, default='media/default_room.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_no',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
